export const categories = [
  {
    id: 1,
    label: "Processeur",
    desc: "Intel, Amd - Tous sockets",
    price: "Prix moyen: 50€ - 800€",
    logo: "🔧",
  },
  {
    id: 2,
    label: "Cartes Graphiques",
    desc: "NVIDIA, AMD - Gaming et pro",
    price: "Prix moyen: 100€ - 2000€",
    logo: "🎮",
  },
  {
    id: 3,
    label: "Mémoire RAM",
    desc: "DDR4, DDR5 - Toutes capacités",
    price: "prix moyen: 30 - 500€",
    logo: "💾",
  },
  {
    id: 4,
    label: "Cartes Mères",
    desc: "ATX, Micro-ATX, Mini-ITX",
    price: "Prix moyen: 60€ - 600€",
    logo: "🖥️",
  },
  {
    id: 5,
    label: "Stockage",
    desc: "SSD, HDD, NVMe",
    price: "Prix moyen: 25€ - 400€",
    logo: "💿",
  },
  {
    id: 6,
    label: "Alimentation",
    desc: "Modulaires et non-modulaires",
    price: "Ventirad, AIO, ventilateurs",
    logo: "⚡",
  },
  {
    id: 7,
    label: "Refroidissement",
    desc: "Ventirad, AIO, ventilateurs",
    price: "Prix moyen: 20€ - 200€",
    logo: "❄️",
  },
  {
    id: 8,
    label: "Boîtiers",
    desc: "Tous formats et designs",
    price: "Prix moyen: 30€ - 200€",
    logo: "📦",
  },
  {
    id: 9,
    label: "Périphériques",
    desc: "Clavier, souris, écrans",
    logo: "🖱️",
  },
];
